'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Go__YouTube_Snagger_Installer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property AxInterop_ShockwaveFlashObjects() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("AxInterop_ShockwaveFlashObjects", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property en_us() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("en_us", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property es_es() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("es_es", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property folder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("folder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fr_fr() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("fr_fr", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Go__YouTube_Snagger() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Go__YouTube_Snagger", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;configuration&gt;
        '''    &lt;configSections&gt;
        '''        &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        '''            &lt;section name=&quot;Go__YouTube_Snagger.My.MySettings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot; /&gt;
        '''        &lt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Go__YouTube_Snagger_exe() As String
            Get
                Return ResourceManager.GetString("Go__YouTube_Snagger_exe", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Go__YouTube_Snagger_Updater() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Go__YouTube_Snagger_Updater", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        '''&lt;configuration&gt;
        '''    &lt;configSections&gt;
        '''        &lt;sectionGroup name=&quot;userSettings&quot; type=&quot;System.Configuration.UserSettingsGroup, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; &gt;
        '''            &lt;section name=&quot;Go__YouTube_Snagger_Updater.My.MySettings&quot; type=&quot;System.Configuration.ClientSettingsSection, System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089&quot; allowExeDefinition=&quot;MachineToLocalUser&quot; requirePermission=&quot;false&quot; /&gt;
        '''  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Go__YouTube_Snagger_Updater_exe() As String
            Get
                Return ResourceManager.GetString("Go__YouTube_Snagger_Updater_exe", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property Google_GData_Client() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Google_GData_Client", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Google_GData_Extensions() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Google_GData_Extensions", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Google_GData_YouTube() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Google_GData_YouTube", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Interop_IWshRuntimeLibrary() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Interop_IWshRuntimeLibrary", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Interop_ShockwaveFlashObjects() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Interop_ShockwaveFlashObjects", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property lock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("lock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property nb_no() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("nb_no", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        Friend ReadOnly Property Reinstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Reinstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Repair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Repair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Uninstall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Uninstall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ysl() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ysl", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
